// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

type BiogMain struct {
	CPersonid            interface{} `json:"c_personid"`
	CName                *string     `json:"c_name"`
	CNameChn             *string     `json:"c_name_chn"`
	CIndexYear           interface{} `json:"c_index_year"`
	CIndexYearTypeCode   *string     `json:"c_index_year_type_code"`
	CIndexYearSourceID   interface{} `json:"c_index_year_source_id"`
	CFemale              interface{} `json:"c_female"`
	CIndexAddrID         interface{} `json:"c_index_addr_id"`
	CIndexAddrTypeCode   interface{} `json:"c_index_addr_type_code"`
	CEthnicityCode       interface{} `json:"c_ethnicity_code"`
	CHouseholdStatusCode interface{} `json:"c_household_status_code"`
	CTribe               *string     `json:"c_tribe"`
	CBirthyear           interface{} `json:"c_birthyear"`
	CByNhCode            interface{} `json:"c_by_nh_code"`
	CByNhYear            interface{} `json:"c_by_nh_year"`
	CByRange             interface{} `json:"c_by_range"`
	CDeathyear           interface{} `json:"c_deathyear"`
	CDyNhCode            interface{} `json:"c_dy_nh_code"`
	CDyNhYear            interface{} `json:"c_dy_nh_year"`
	CDyRange             interface{} `json:"c_dy_range"`
	CDeathAge            interface{} `json:"c_death_age"`
	CDeathAgeRange       interface{} `json:"c_death_age_range"`
	CFlEarliestYear      interface{} `json:"c_fl_earliest_year"`
	CFlEyNhCode          interface{} `json:"c_fl_ey_nh_code"`
	CFlEyNhYear          interface{} `json:"c_fl_ey_nh_year"`
	CFlEyNotes           *string     `json:"c_fl_ey_notes"`
	CFlLatestYear        interface{} `json:"c_fl_latest_year"`
	CFlLyNhCode          interface{} `json:"c_fl_ly_nh_code"`
	CFlLyNhYear          interface{} `json:"c_fl_ly_nh_year"`
	CFlLyNotes           *string     `json:"c_fl_ly_notes"`
	CSurname             *string     `json:"c_surname"`
	CSurnameChn          *string     `json:"c_surname_chn"`
	CMingzi              *string     `json:"c_mingzi"`
	CMingziChn           *string     `json:"c_mingzi_chn"`
	CDy                  interface{} `json:"c_dy"`
	CChoronymCode        interface{} `json:"c_choronym_code"`
	CNotes               *string     `json:"c_notes"`
	CByIntercalary       interface{} `json:"c_by_intercalary"`
	CDyIntercalary       interface{} `json:"c_dy_intercalary"`
	CByMonth             interface{} `json:"c_by_month"`
	CDyMonth             interface{} `json:"c_dy_month"`
	CByDay               interface{} `json:"c_by_day"`
	CDyDay               interface{} `json:"c_dy_day"`
	CByDayGz             interface{} `json:"c_by_day_gz"`
	CDyDayGz             interface{} `json:"c_dy_day_gz"`
	CSurnameProper       *string     `json:"c_surname_proper"`
	CMingziProper        *string     `json:"c_mingzi_proper"`
	CNameProper          *string     `json:"c_name_proper"`
	CSurnameRm           *string     `json:"c_surname_rm"`
	CMingziRm            *string     `json:"c_mingzi_rm"`
	CNameRm              *string     `json:"c_name_rm"`
	CCreatedBy           *string     `json:"c_created_by"`
	CModifiedBy          *string     `json:"c_modified_by"`
	CCreatedDate         *string     `json:"c_created_date"`
	CModifiedDate        *string     `json:"c_modified_date"`
}
