// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package repository

import (
	"context"
)

const getPersonByID = `-- name: GetPersonByID :one
select c_personid, c_name_chn
from BIOG_MAIN
where c_personid = ?
`

type GetPersonByIDRow struct {
	CPersonid interface{} `json:"c_personid"`
	CNameChn  *string     `json:"c_name_chn"`
}

func (q *Queries) GetPersonByID(ctx context.Context, cPersonid interface{}) (GetPersonByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getPersonByID, cPersonid)
	var i GetPersonByIDRow
	err := row.Scan(&i.CPersonid, &i.CNameChn)
	return i, err
}
