// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package repository

import (
	"context"
)

const getAltnamesByPersonID = `-- name: GetAltnamesByPersonID :many
select 
ad.c_alt_name as altname_en,
ad.c_alt_name_chn as altname_ch,
ac.c_name_type_desc as name_type,
ac.c_name_type_desc_chn as name_type_ch
from 
ALTNAME_DATA ad 
join ALTNAME_CODES ac on ad.c_alt_name_type_code = ac.c_name_type_code 
where ad.c_personid = ?
`

type GetAltnamesByPersonIDRow struct {
	AltnameEn  *string `json:"altname_en"`
	AltnameCh  string  `json:"altname_ch"`
	NameType   *string `json:"name_type"`
	NameTypeCh *string `json:"name_type_ch"`
}

func (q *Queries) GetAltnamesByPersonID(ctx context.Context, cPersonid int64) ([]GetAltnamesByPersonIDRow, error) {
	rows, err := q.db.QueryContext(ctx, getAltnamesByPersonID, cPersonid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAltnamesByPersonIDRow
	for rows.Next() {
		var i GetAltnamesByPersonIDRow
		if err := rows.Scan(
			&i.AltnameEn,
			&i.AltnameCh,
			&i.NameType,
			&i.NameTypeCh,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAssociationByPersonID = `-- name: GetAssociationByPersonID :many
SELECT
ad.c_assoc_id as assoc_id,
ad.c_text_title as text_title,
bm.c_name as name_en,
bm.c_name_chn as name_ch,
ad.c_assoc_first_year as assoc_first_year,
ad.c_assoc_last_year as assoc_last_year,
ac.c_assoc_desc_chn as assoc_cn,
ac.c_assoc_pair as assoc_pair,
ad.c_notes as notes,
ad.c_pages as pages,
tc.c_title_chn as title_ch,
t.c_assoc_type_desc as assoc_type_en,
t.c_assoc_type_desc_chn as assoc_type_ch,
t.c_assoc_type_short_desc as assoc_type_short
FROM 
ASSOC_DATA ad 
LEFT JOIN BIOG_MAIN bm on ad.c_assoc_id = bm.c_personid 
LEFT JOIN ASSOC_CODES ac on ad.c_assoc_code  = ac.c_assoc_code 
LEFT JOIN TEXT_CODES tc  on ad.c_source = tc.c_textid 
LEFT JOIN ASSOC_CODE_TYPE_REL actr on actr.c_assoc_code = ac.c_assoc_code 
LEFT JOIN ASSOC_TYPES t on t.c_assoc_type_code = actr.c_assoc_type_code 
WHERE ad.c_personid = ?
`

type GetAssociationByPersonIDRow struct {
	AssocID        int64   `json:"assoc_id"`
	TextTitle      string  `json:"text_title"`
	NameEn         *string `json:"name_en"`
	NameCh         *string `json:"name_ch"`
	AssocFirstYear int16   `json:"assoc_first_year"`
	AssocLastYear  *int16  `json:"assoc_last_year"`
	AssocCn        *string `json:"assoc_cn"`
	AssocPair      *int16  `json:"assoc_pair"`
	Notes          *string `json:"notes"`
	Pages          *string `json:"pages"`
	TitleCh        *string `json:"title_ch"`
	AssocTypeEn    *string `json:"assoc_type_en"`
	AssocTypeCh    *string `json:"assoc_type_ch"`
	AssocTypeShort *string `json:"assoc_type_short"`
}

func (q *Queries) GetAssociationByPersonID(ctx context.Context, cPersonid int64) ([]GetAssociationByPersonIDRow, error) {
	rows, err := q.db.QueryContext(ctx, getAssociationByPersonID, cPersonid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAssociationByPersonIDRow
	for rows.Next() {
		var i GetAssociationByPersonIDRow
		if err := rows.Scan(
			&i.AssocID,
			&i.TextTitle,
			&i.NameEn,
			&i.NameCh,
			&i.AssocFirstYear,
			&i.AssocLastYear,
			&i.AssocCn,
			&i.AssocPair,
			&i.Notes,
			&i.Pages,
			&i.TitleCh,
			&i.AssocTypeEn,
			&i.AssocTypeCh,
			&i.AssocTypeShort,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEntryByPersonID = `-- name: GetEntryByPersonID :many
SELECT
ed.c_age as age,
ed.c_year as year,
et.c_entry_type_desc as entry_type_en,
ec.c_entry_desc_chn as entry_ch,
et.c_entry_type_level as entry_type_level,
et.c_entry_type_desc_chn as entry_type_level_ch,
ed.c_exam_rank as exam_rank
FROM
ENTRY_DATA ed 
join ENTRY_CODES ec on ec.c_entry_code  = ed.c_entry_code 
join ENTRY_CODE_TYPE_REL ectr on ectr.c_entry_code = ec.c_entry_code 
join ENTRY_TYPES et on et.c_entry_type = ectr.c_entry_type 
where ed.c_personid = ?
`

type GetEntryByPersonIDRow struct {
	Age              *int16  `json:"age"`
	Year             int16   `json:"year"`
	EntryTypeEn      string  `json:"entry_type_en"`
	EntryCh          string  `json:"entry_ch"`
	EntryTypeLevel   *int16  `json:"entry_type_level"`
	EntryTypeLevelCh string  `json:"entry_type_level_ch"`
	ExamRank         *string `json:"exam_rank"`
}

// join NIAN_HAO nh on nh.c_nianhao_id = ed.c_entry_nh_id
func (q *Queries) GetEntryByPersonID(ctx context.Context, cPersonid int64) ([]GetEntryByPersonIDRow, error) {
	rows, err := q.db.QueryContext(ctx, getEntryByPersonID, cPersonid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetEntryByPersonIDRow
	for rows.Next() {
		var i GetEntryByPersonIDRow
		if err := rows.Scan(
			&i.Age,
			&i.Year,
			&i.EntryTypeEn,
			&i.EntryCh,
			&i.EntryTypeLevel,
			&i.EntryTypeLevelCh,
			&i.ExamRank,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getInstitutionByPersonID = `-- name: GetInstitutionByPersonID :many
SELECT 
sinc.c_inst_name_hz as inst_name_hz,
sinc.c_inst_name_py as inst_name_py,
bic.c_bi_role_desc as bi_role_en,
bic.c_bi_role_chn as bi_role_ch,
bid.c_bi_begin_year as bi_begin_year,
bid.c_bi_end_year as bi_end_year,
tc.c_title as title,
tc.c_title_chn as title_chn,
bid.c_pages as pages
FROM
BIOG_INST_DATA bid 
LEFT JOIN BIOG_MAIN bm on bm.c_personid = bid.c_personid 
LEFT JOIN SOCIAL_INSTITUTION_NAME_CODES sinc on bid.c_inst_name_code = sinc.c_inst_name_code 
LEFT JOIN SOCIAL_INSTITUTION_CODES sic on sic.c_inst_code = bid.c_inst_code
LEFT JOIN BIOG_INST_CODES bic on bic.c_bi_role_code = bid.c_bi_role_code 
LEFT JOIN TEXT_CODES tc on tc.c_textid  = bid.c_source 
where bid.c_personid = ?
ORDER BY bid.c_bi_begin_year
`

type GetInstitutionByPersonIDRow struct {
	InstNameHz  *string `json:"inst_name_hz"`
	InstNamePy  *string `json:"inst_name_py"`
	BiRoleEn    *string `json:"bi_role_en"`
	BiRoleCh    *string `json:"bi_role_ch"`
	BiBeginYear *int16  `json:"bi_begin_year"`
	BiEndYear   *int16  `json:"bi_end_year"`
	Title       *string `json:"title"`
	TitleChn    *string `json:"title_chn"`
	Pages       *string `json:"pages"`
}

// LEFT JOIN SOCIAL_INSTITUTION_ADDR sia on sia.c_inst_code = bid.c_inst_code
func (q *Queries) GetInstitutionByPersonID(ctx context.Context, cPersonid int64) ([]GetInstitutionByPersonIDRow, error) {
	rows, err := q.db.QueryContext(ctx, getInstitutionByPersonID, cPersonid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetInstitutionByPersonIDRow
	for rows.Next() {
		var i GetInstitutionByPersonIDRow
		if err := rows.Scan(
			&i.InstNameHz,
			&i.InstNamePy,
			&i.BiRoleEn,
			&i.BiRoleCh,
			&i.BiBeginYear,
			&i.BiEndYear,
			&i.Title,
			&i.TitleChn,
			&i.Pages,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPersonBasicInfoByID = `-- name: GetPersonBasicInfoByID :one
select 
bm.c_personid AS person_id,
bm.c_name AS name_en,
bm.c_name_chn As name_ch,
bm.c_mingzi AS mingzi,
bm.c_female AS female,
bm.c_birthyear as birth_year,
bm.c_deathyear as death_year,
d.c_dynasty as dynasty_en,
d.c_dynasty_chn as dynasty_ch,
cc.c_choronym_desc as choronym_en,
cc.c_choronym_chn as choronym_ch
from BIOG_MAIN bm 
left join DYNASTIES d on bm.c_dy = d.c_dy 
left join CHORONYM_CODES cc on bm.c_choronym_code = cc.c_choronym_code 
where bm.c_personid = ?
`

type GetPersonBasicInfoByIDRow struct {
	PersonID   int64   `json:"person_id"`
	NameEn     *string `json:"name_en"`
	NameCh     *string `json:"name_ch"`
	Mingzi     *string `json:"mingzi"`
	Female     *int16  `json:"female"`
	BirthYear  *int16  `json:"birth_year"`
	DeathYear  *int16  `json:"death_year"`
	DynastyEn  *string `json:"dynasty_en"`
	DynastyCh  *string `json:"dynasty_ch"`
	ChoronymEn *string `json:"choronym_en"`
	ChoronymCh *string `json:"choronym_ch"`
}

func (q *Queries) GetPersonBasicInfoByID(ctx context.Context, cPersonid int64) (GetPersonBasicInfoByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getPersonBasicInfoByID, cPersonid)
	var i GetPersonBasicInfoByIDRow
	err := row.Scan(
		&i.PersonID,
		&i.NameEn,
		&i.NameCh,
		&i.Mingzi,
		&i.Female,
		&i.BirthYear,
		&i.DeathYear,
		&i.DynastyEn,
		&i.DynastyCh,
		&i.ChoronymEn,
		&i.ChoronymCh,
	)
	return i, err
}

const getPersonByName = `-- name: GetPersonByName :many
SELECT
bm.c_personid AS person_id,
bm.c_name AS name_en,
bm.c_name_chn AS name_ch,
bm.c_birthyear AS birth_year,
bm.c_deathyear AS death_year,
d.c_dynasty AS dynasty_en,
d.c_dynasty_chn AS dynasty_ch,
d.c_start AS dynasty_start,
d.c_end AS dynasty_end
FROM 
BIOG_MAIN bm 
join DYNASTIES d on bm.c_dy = d.c_dy 
WHERE bm.c_name_chn = CAST(?1 AS text)
OR 
bm.c_name like CAST(?1 AS text)
`

type GetPersonByNameRow struct {
	PersonID     int64   `json:"person_id"`
	NameEn       *string `json:"name_en"`
	NameCh       *string `json:"name_ch"`
	BirthYear    *int16  `json:"birth_year"`
	DeathYear    *int16  `json:"death_year"`
	DynastyEn    *string `json:"dynasty_en"`
	DynastyCh    *string `json:"dynasty_ch"`
	DynastyStart int16   `json:"dynasty_start"`
	DynastyEnd   int16   `json:"dynasty_end"`
}

func (q *Queries) GetPersonByName(ctx context.Context, name string) ([]GetPersonByNameRow, error) {
	rows, err := q.db.QueryContext(ctx, getPersonByName, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPersonByNameRow
	for rows.Next() {
		var i GetPersonByNameRow
		if err := rows.Scan(
			&i.PersonID,
			&i.NameEn,
			&i.NameCh,
			&i.BirthYear,
			&i.DeathYear,
			&i.DynastyEn,
			&i.DynastyCh,
			&i.DynastyStart,
			&i.DynastyEnd,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPersonKinShipByPersonID = `-- name: GetPersonKinShipByPersonID :many
select 
kd.c_kin_id as kin_id,
kc.c_kinrel as kin_rel_en, 
kc.c_kinrel_alt as kin_alt, 
kc.c_kinrel_chn as kin_rel_ch, 
bm.c_name as name,
bm.c_name_chn as name_ch
from KIN_DATA kd
join BIOG_MAIN bm on bm.c_personid = kd.c_kin_id 
join KINSHIP_CODES kc on kd.c_kin_code = kc.c_kincode 
where kd.c_personid = ?
`

type GetPersonKinShipByPersonIDRow struct {
	KinID    int64   `json:"kin_id"`
	KinRelEn string  `json:"kin_rel_en"`
	KinAlt   *string `json:"kin_alt"`
	KinRelCh string  `json:"kin_rel_ch"`
	Name     *string `json:"name"`
	NameCh   *string `json:"name_ch"`
}

func (q *Queries) GetPersonKinShipByPersonID(ctx context.Context, cPersonid int64) ([]GetPersonKinShipByPersonIDRow, error) {
	rows, err := q.db.QueryContext(ctx, getPersonKinShipByPersonID, cPersonid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPersonKinShipByPersonIDRow
	for rows.Next() {
		var i GetPersonKinShipByPersonIDRow
		if err := rows.Scan(
			&i.KinID,
			&i.KinRelEn,
			&i.KinAlt,
			&i.KinRelCh,
			&i.Name,
			&i.NameCh,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPlaceByPersonID = `-- name: GetPlaceByPersonID :many
;

SELECT
ac.c_name as name_en,
ac.c_name_chn as name_ch,
bac.c_addr_desc as addr_en,
bac.c_addr_desc_chn as addr_ch,
ac.c_admin_type as admin_type,
bad.c_firstyear as first_year,
bad.c_lastyear as last_year,
bad.c_notes as notes,
ac.x_coord as x_coord,
ac.y_coord as y_coord,
tc.c_title_chn as title_ch,
bad.c_pages as pages
FROM
BIOG_ADDR_DATA bad 
LEFT JOIN ADDR_CODES ac on ac.c_addr_id = bad.c_addr_id 
LEFT JOIN BIOG_ADDR_CODES bac on bac.c_addr_type = bad.c_addr_type 
LEFT JOIN TEXT_CODES tc on bad.c_source = tc.c_textid 
LEFT JOIN ADDR_BELONGS_DATA abd on abd.c_addr_id = bad.c_addr_id 
where bad.c_personid = ?
ORDER BY bad.c_firstyear
`

type GetPlaceByPersonIDRow struct {
	NameEn    *string  `json:"name_en"`
	NameCh    *string  `json:"name_ch"`
	AddrEn    *string  `json:"addr_en"`
	AddrCh    *string  `json:"addr_ch"`
	AdminType *string  `json:"admin_type"`
	FirstYear *int16   `json:"first_year"`
	LastYear  *int16   `json:"last_year"`
	Notes     *string  `json:"notes"`
	XCoord    *float64 `json:"x_coord"`
	YCoord    *float64 `json:"y_coord"`
	TitleCh   *string  `json:"title_ch"`
	Pages     *string  `json:"pages"`
}

func (q *Queries) GetPlaceByPersonID(ctx context.Context, cPersonid int64) ([]GetPlaceByPersonIDRow, error) {
	rows, err := q.db.QueryContext(ctx, getPlaceByPersonID, cPersonid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPlaceByPersonIDRow
	for rows.Next() {
		var i GetPlaceByPersonIDRow
		if err := rows.Scan(
			&i.NameEn,
			&i.NameCh,
			&i.AddrEn,
			&i.AddrCh,
			&i.AdminType,
			&i.FirstYear,
			&i.LastYear,
			&i.Notes,
			&i.XCoord,
			&i.YCoord,
			&i.TitleCh,
			&i.Pages,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPostingByPersonID = `-- name: GetPostingByPersonID :many
WITH ptod AS (
	SELECT c_personid, c_office_id, c_posting_id, c_sequence, c_firstyear, c_fy_nh_code, c_fy_nh_year, c_fy_range, c_lastyear, c_ly_nh_code, c_ly_nh_year, c_ly_range, c_appt_code, c_assume_office_code, c_inst_code, c_inst_name_code, c_source, c_pages, c_notes, c_office_id_backup, c_office_category_id, c_fy_intercalary, c_fy_month, c_ly_intercalary, c_ly_month, c_fy_day, c_ly_day, c_fy_day_gz, c_ly_day_gz, c_dy, c_created_by, c_modified_by, c_created_date, c_modified_date FROM POSTED_TO_OFFICE_DATA WHERE c_personid = CAST(?1 AS INTEGER)
)
SELECT 
ac.c_appt_desc as appt_en,
ac.c_appt_desc_chn as appt_cn,
oc2.c_office_chn as office_ch,
oc2.c_office_chn_alt as office_ch_alt,
ptod.c_firstyear as first_year,
ptod.c_lastyear as last_year,
tc.c_title_chn as title_ch
FROM 
POSTING_DATA pd 
join ptod on ptod.c_posting_id = pd.c_posting_id
join APPOINTMENT_CODES ac on ac.c_appt_code = ptod.c_appt_code 
LEFT join OFFICE_CATEGORIES oc on oc.c_office_category_id = ptod.c_office_category_id 
join OFFICE_CODES oc2 on oc2.c_office_id = ptod.c_office_id 
LEFT JOIN TEXT_CODES tc on ptod.c_source = tc.c_textid 
where pd.c_personid = CAST(?1 AS INTEGER)
ORDER BY ptod.c_firstyear
`

type GetPostingByPersonIDRow struct {
	ApptEn      *string `json:"appt_en"`
	ApptCn      *string `json:"appt_cn"`
	OfficeCh    *string `json:"office_ch"`
	OfficeChAlt *string `json:"office_ch_alt"`
	FirstYear   *int16  `json:"first_year"`
	LastYear    *int16  `json:"last_year"`
	TitleCh     *string `json:"title_ch"`
}

func (q *Queries) GetPostingByPersonID(ctx context.Context, personID int64) ([]GetPostingByPersonIDRow, error) {
	rows, err := q.db.QueryContext(ctx, getPostingByPersonID, personID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPostingByPersonIDRow
	for rows.Next() {
		var i GetPostingByPersonIDRow
		if err := rows.Scan(
			&i.ApptEn,
			&i.ApptCn,
			&i.OfficeCh,
			&i.OfficeChAlt,
			&i.FirstYear,
			&i.LastYear,
			&i.TitleCh,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStatusByPersonID = `-- name: GetStatusByPersonID :many
SELECT 
sc.c_status_desc as status_en,
sc.c_status_desc_chn as status_ch
FROM
STATUS_DATA sd 
join STATUS_CODES sc on sd.c_status_code = sc.c_status_code 
where sd.c_personid = ?
`

type GetStatusByPersonIDRow struct {
	StatusEn string `json:"status_en"`
	StatusCh string `json:"status_ch"`
}

func (q *Queries) GetStatusByPersonID(ctx context.Context, cPersonid int64) ([]GetStatusByPersonIDRow, error) {
	rows, err := q.db.QueryContext(ctx, getStatusByPersonID, cPersonid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetStatusByPersonIDRow
	for rows.Next() {
		var i GetStatusByPersonIDRow
		if err := rows.Scan(&i.StatusEn, &i.StatusCh); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTextByPersonID = `-- name: GetTextByPersonID :many
SELECT
tc.c_title_chn as title_ch,
tc.c_text_year as text_year,
tc.c_source as source,
tc2.c_title_chn as source_title
FROM
BIOG_TEXT_DATA btd 
JOIN TEXT_CODES tc on tc.c_textid  = btd.c_textid 
LEFT JOIN TEXT_CODES tc2 on tc.c_source = tc2.c_textid 
WHERE btd.c_personid = ?
`

type GetTextByPersonIDRow struct {
	TitleCh     *string `json:"title_ch"`
	TextYear    *int16  `json:"text_year"`
	Source      *int64  `json:"source"`
	SourceTitle *string `json:"source_title"`
}

func (q *Queries) GetTextByPersonID(ctx context.Context, cPersonid int64) ([]GetTextByPersonIDRow, error) {
	rows, err := q.db.QueryContext(ctx, getTextByPersonID, cPersonid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTextByPersonIDRow
	for rows.Next() {
		var i GetTextByPersonIDRow
		if err := rows.Scan(
			&i.TitleCh,
			&i.TextYear,
			&i.Source,
			&i.SourceTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
