CREATE TABLE BIOG_MAIN (
    "c_personid" INTEGER NOT NULL,
    "c_name" varchar(255) DEFAULT NULL /* Hanyu Pinyin full name; auto-generated: c_surname + " " + c_mingzi */,
    "c_name_chn" varchar(255) DEFAULT NULL /* Chinese full name; auto-generated: c_surname_chn + c_mingzi_chn (no space) */,
    "c_index_year" smallint(6) DEFAULT NULL,
    "c_index_year_type_code" varchar(255) DEFAULT NULL,
    "c_index_year_source_id" INTEGER(11) DEFAULT NULL,
    "c_female" smallint(6) DEFAULT NULL,
    "c_index_addr_id" INTEGER(11) DEFAULT 0,
    "c_index_addr_type_code" smallint(6) DEFAULT NULL,
    "c_ethnicity_code" smallint(6) DEFAULT NULL,
    "c_household_status_code" smallint(6) DEFAULT NULL,
    "c_tribe" varchar(255) DEFAULT NULL,
    "c_birthyear" smallint(6) DEFAULT NULL,
    "c_by_nh_code" smallint(6) DEFAULT NULL,
    "c_by_nh_year" smallint(6) DEFAULT NULL,
    "c_by_range" smallint(6) DEFAULT NULL,
    "c_deathyear" smallint(6) DEFAULT NULL,
    "c_dy_nh_code" smallint(6) DEFAULT NULL,
    "c_dy_nh_year" smallint(6) DEFAULT NULL,
    "c_dy_range" smallint(6) DEFAULT NULL,
    "c_death_age" smallint(6) DEFAULT NULL,
    "c_death_age_range" smallint(6) DEFAULT NULL,
    "c_fl_earliest_year" smallint(6) DEFAULT NULL,
    "c_fl_ey_nh_code" smallint(6) DEFAULT NULL,
    "c_fl_ey_nh_year" smallint(6) DEFAULT NULL,
    "c_fl_ey_notes" TEXT DEFAULT NULL,
    "c_fl_latest_year" smallint(6) DEFAULT NULL,
    "c_fl_ly_nh_code" smallint(6) DEFAULT NULL,
    "c_fl_ly_nh_year" smallint(6) DEFAULT NULL,
    "c_fl_ly_notes" TEXT DEFAULT NULL,
    "c_surname" varchar(255) DEFAULT NULL /* Hanyu Pinyin romanization of the person's surname; auto-generated from c_surname_chn via pinyin lookup table */,
    "c_surname_chn" varchar(255) DEFAULT NULL /* Chinese surname; split from c_name_chn by matching longest known surname in pinyin table */,
    "c_mingzi" varchar(255) DEFAULT NULL /* Hanyu Pinyin romanization of the person's given name (excluding surname); auto-generated from c_mingzi_chn */,
    "c_mingzi_chn" varchar(255) DEFAULT NULL /* Chinese given name (excluding surname); remainder of c_name_chn after surname extraction */,
    "c_dy" smallint(6) DEFAULT NULL,
    "c_choronym_code" smallint(6) DEFAULT NULL,
    "c_notes" TEXT DEFAULT NULL,
    "c_by_intercalary" smallint(6) DEFAULT NULL,
    "c_dy_intercalary" smallint(6) DEFAULT NULL,
    "c_by_month" smallint(6) DEFAULT NULL,
    "c_dy_month" smallint(6) DEFAULT NULL,
    "c_by_day" smallint(6) DEFAULT NULL,
    "c_dy_day" smallint(6) DEFAULT NULL,
    "c_by_day_gz" smallint(6) DEFAULT NULL,
    "c_dy_day_gz" smallint(6) DEFAULT NULL,
    "c_surname_proper" varchar(255) DEFAULT NULL /* Surname in the person's native language (non-Chinese), if applicable; user-editable */,
    "c_mingzi_proper" varchar(255) DEFAULT NULL /* Given name in the person's native language (non-Chinese, excluding surname), if applicable; user-editable */,
    "c_name_proper" varchar(255) DEFAULT NULL /* Full name in the person's native language; auto-generated: c_mingzi_proper + " " + c_surname_proper (given-name-first order) */,
    "c_surname_rm" varchar(255) DEFAULT NULL /* Non-Pinyin romanization of the person's surname (e.g. Wade-Giles, McCune-Reischauer), if applicable; user-editable */,
    "c_mingzi_rm" varchar(255) DEFAULT NULL /* Non-Pinyin romanization of the person's given name (excluding surname), if applicable; user-editable */,
    "c_name_rm" varchar(255) DEFAULT NULL /* Non-Pinyin romanized full name; auto-generated: c_mingzi_rm + " " + c_surname_rm (given-name-first order) */,
    "c_created_by" varchar(255) DEFAULT NULL,
    "c_modified_by" varchar(255) DEFAULT NULL,
    "c_created_date" TEXT DEFAULT NULL,
    "c_modified_date" TEXT DEFAULT NULL,
    PRIMARY KEY ("c_personid")
);

CREATE TABLE KIN_DATA (
    "c_personid" INTEGER(11) NOT NULL,
    "c_kin_id" INTEGER(11) NOT NULL,
    "c_kin_code" smallint(6) NOT NULL,
    "c_source" INTEGER(11) DEFAULT NULL,
    "c_pages" varchar(255) DEFAULT NULL,
    "c_notes" TEXT DEFAULT NULL,
    "c_autogen_notes" TEXT DEFAULT NULL,
    "c_created_by" varchar(255) DEFAULT NULL,
    "c_modified_by" varchar(255) DEFAULT NULL,
    "c_created_date" TEXT DEFAULT NULL,
    "c_modified_date" TEXT DEFAULT NULL,
    PRIMARY KEY ("c_kin_code", "c_kin_id", "c_personid")
);

CREATE TABLE KINSHIP_CODES (
    "c_kincode" smallint(6) NOT NULL,
    "c_kin_pair1" smallint(6) NOT NULL DEFAULT 0,
    "c_kin_pair2" smallint(6) NOT NULL DEFAULT 0,
    "c_kin_pair_notes" varchar(255) DEFAULT NULL,
    "c_kinrel_chn" varchar(255) NOT NULL DEFAULT '',
    "c_kinrel" varchar(255) NOT NULL DEFAULT '',
    "c_kinrel_alt" varchar(255) DEFAULT NULL,
    "c_pick_sorting" smallint(6) DEFAULT NULL,
    "c_upstep" smallint(6) NOT NULL DEFAULT 0,
    "c_dwnstep" smallint(6) NOT NULL DEFAULT 0,
    "c_marstep" smallint(6) NOT NULL DEFAULT 0,
    "c_colstep" smallint(6) NOT NULL DEFAULT 0,
    "c_kinrel_simplified" varchar(255) NOT NULL DEFAULT '',
    PRIMARY KEY ("c_kincode")
);

CREATE TABLE DYNASTIES (
    "c_dy" smallint(6) NOT NULL,
    "c_dynasty" varchar(255) DEFAULT NULL,
    "c_dynasty_chn" varchar(255) DEFAULT NULL,
    "c_start" smallint(6) NOT NULL DEFAULT 0,
    "c_end" smallint(6) NOT NULL DEFAULT 0,
    "c_sort" smallint(6) DEFAULT NULL,
    PRIMARY KEY ("c_dy")
);

CREATE TABLE CHORONYM_CODES (
    "c_choronym_code" smallint(6) NOT NULL,
    "c_choronym_desc" varchar(255) DEFAULT NULL,
    "c_choronym_chn" varchar(255) DEFAULT NULL,
    PRIMARY KEY ("c_choronym_code")
);
